/*
 * USBHub.hh
 *
 *  Created on: 27.08.2015
 *      Author: Daniel
 */

#ifndef SOURCE_ARCH_SHARED_USB_USBHUB_HH_
#define SOURCE_ARCH_SHARED_USB_USBHUB_HH_

#include "USBDeviceDriver.hh"
#include "USBHostController.hh"


#define USB_DEVICE_SPEED_FULL  0
#define USB_DEVICE_SPEED_LOW   1
#define USB_DEVICE_SPEED_HIGH  2

class USBHub: public USBDeviceDriver {
public:
    USBHub(USBDevice *dev, USB_Host_Controller *controller);

    virtual ~USBHub();

private:
    // The USB Device representing the hub
    USBDevice*              dev;

    // The hub descriptor received during enumeration
    HubDescriptor           hub_descr;

    // The Controller used to communicate with this hub
    USB_Host_Controller*    controller;

    // The devices attached to the ports.. maximum 6 ports
    USBDevice*              portDevices[6];

    /*****************************************************************************
     * Method: handleStatusChange()
     *
     * @description
     *  Handles USB HUB status changes.
     *******************************************************************************/
    void handleStatusChange();

public:
    /*****************************************************************************
     * Method: initialize()
     *
     * @description
     *  Hub initialization.
     *******************************************************************************/
    ErrorT initialize() {
        return (cOk);
    }

    /*****************************************************************************
     * Method: resetPort(int port)
     *
     * @description
     *  Resets the given port. As port speed detection
     *  is part of the reset procedure the port speed
     *  is returned on success.
     *
     * @return
     *  ErrorCode < 0 if error occurred
     *  Detected speed of attached Devices on success.
     *******************************************************************************/
    ErrorT resetPort(int port);

    /*****************************************************************************
     * Method: handleInterrupt()
     *
     * @description
     *  Handles IRQs generated by the USB HUB
     *******************************************************************************/
    ErrorT handleInterrupt();

    USBDevice* getDevice() {
        return (dev);
    }

    /*****************************************************************************
     * Method: enumerate()
     *
     * @description
     *  Issues a USB HUB enumeration, possibly identifying new usb
     *  devices.
     *******************************************************************************/
    ErrorT enumerate();
};


#endif /* SOURCE_ARCH_SHARED_USB_USBHUB_HH_ */
