#
# arch.mk contains all architecture dependent makefile-settings, as kernel.mk must not contain any of them.
#

#ARCH_OBJ contains all architecture dependent object files to be compiled and linked into the kernel.
#The following object files are mandatory for this architecture
#Optional and configured object file targets are auto generated by the SCL tool in scl_make.mk
ARCH_OBJ += _startup.o MicroFunkBoard.o ATMEGA328Processor.o assemblerFunctions.o startThread.o


#ARCH_VPATH defines architecture dependent VPATH-entries (see VPATH below).
ARCH_VPATH = $(KERNEL_DIR)arch/Atmel/ $(KERNEL_DIR)arch/Atmel/ATMEGA328/ $(KERNEL_DIR)arch/Atmel/ATMEGA328/RN-MicroFunk/

#Where to look for header files in the architecture directories.
ARCH_INCLUDES = -I$(KERNEL_DIR)arch/Atmel/ -I$(KERNEL_DIR)arch/Atmel/ATMEGA328/ -I$(KERNEL_DIR)arch/Atmel/ATMEGA328/RN-MicroFunk/

UIMAGE_ARCH=avr32
