OUTPUTFILE 			= telnet_server

# Define the target ISA here if not provided from outside environment variable
TARGET				= armv7

ORCOS_LIB_DIR 		= D:/git/orcos_github/library/
KEEP_TEMP_FILES 	= 1

INITIAL_PRIORITY 	= 1000
PHASE				= 0
PERIOD 				= 0
DEADLINE 			= 0
EXECUTIONTIME 		= 0
STACK_SIZE 			= 4096

BUILD_CRC32			= 1

POST_BUILD			= 

-include $(ORCOS_LIB_DIR)/Makefile.mk